
namespace: labs-dev
# Labels dont work as expected yet
labels_enabled: true
route: true

# build orc
orchestrator:
  name: orc
  enabled: true

chitchat:
  name: chtchat
  enabled: true


# postgresql:
#   enabled: true
#   accessmode: ReadWriteOnce
#   service:
#     port: 5432
#     type: ClusterIP
#   image:
#     tag: "9.6"

#   storageClass:
#   accessMode: ReadWriteOnce
#   size: 5Gi

#   # To use an external secret for the password for an external PostgreSQL
#   # instance, set enabled to false and provide the name of the secret on the
#   # line below:
#   # existingSecret: ""
#   username: "bastian"
#   password: "balthazar"
#   database: "interakt_backend"

#   ## Set annotations on pvc
#   annotations: {}

# rerankerBuild:
#   build_tag: latest
#   base_image: python-37:latest
#   enabled: true
#   source_docker_file_path: ./WHO-FAQ-Rerank-Engine/Dockerfile

botpress:
  name: bp
  enabled: true

solr:
  name: solr
  enabled: true
  route_enabled: false

mongo:
  name: mongo
  enabled: false
  route_enabled: false

# reranker:
#   dcName: reranker-dc
#   routeName: reranker-route
#   serviceName: reranker-service
#   enabled: true
#   minReplicas: 1
#   maxReplicas: 2
#   target:
#     apiVersion: apps.openshift.io/v1
#     kind: DeploymentConfig
#   cpuTarget: 1000m
#   memTarget: 500Mi

# Horizontal Pod Autoscaler
# hpa:
#   enabled: false
#   target:
#     apiVersion: apps.openshift.io/v1
#     kind: DeploymentConfig
#   minReplicas: 1
#   maxReplicas: 2
#   cpuTarget: 1000m
#   memTarget: 500Mi

redis:
  name: redis
  enabled: true
  memory_limit: 512Mi
  is_namespace: openshift
  redis_password: 'password'
  redis_version: "5"
  volume_capacity: 1Gi
  service:
    port: 6379

storage:
  enabled: false
  volume_capacity: 100Mi
  storageClassName: azure-file-storage
  mountPath: /opt/app-root/src/vla/media