apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.orchestrator.serviceName }}
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: orchestrator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5009