from setuptools import setup, find_packages

setup(name='orchestrator',
      version='1.0.2',
      packages=find_packages(),
    #   package_data={'': ['./nginx-orchestrator-setup/Dockerfile']},
    #   include_package_data = True,
      install_requires=[
        #   'tokenizers==0.7',
        #   'transformers==2.10.0',
        #   'torch==1.5.0',
        #   'flask==1.1.2',
        #   'pandas==1.1.1',
        #   'tensorflow==2.3.0',
        #   'xlrd==1.2.0',
        #   'numpy==1.18',
        #   'Flask-Caching==1.9.0',
        #   'Flask-Limiter==1.4',
        #   'spacy==2.3.2',
        #   'spacy-wordnet==0.0.4',
        #   'sklearn==0.0',
        #   'pysolr==3.9.0', 
        #   'strsim==0.0.3', 
        #   'gunicorn==20.0.4',
        #   'pytest', 
        #   'python-dotenv==0.15.0',
        #   'redis', 
        #   'gevent',
      ])