# {{- if .Values.enabled }}
# apiVersion: v1
# kind: Secret
# metadata:
#   annotations:
#     template.openshift.io/expose-admin_password: '{.data[''database-admin-password'']}'
#     template.openshift.io/expose-database_name: '{.data[''database-name'']}'
#     template.openshift.io/expose-password: '{.data[''database-password'']}'
#     template.openshift.io/expose-username: '{.data[''database-user'']}'
#   name: {{ include "mongodb.fullname" . }}
#   labels:
#     {{- include "mongodb.labels" . | nindent 6 }}
# stringData:
#   database-admin-password: {{ .Values.database.adminPassword | quote }}
#   database-name: {{ .Values.database.name | quote }}
#   database-password: {{ .Values.database.password | quote }}
#   database-user: {{ .Values.database.user | quote }}
# {{- end }}