{{- if .Values.mongo.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: mongodb://{.spec.clusterIP}:{.spec.ports[?(.name=="mongo")].port}
  name: {{ include "mongodb.fullname" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 6 }}
spec:
  ports:
  - name: mongo
    nodePort: 0
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 6 }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
{{- end }}