{{- if .Values.botpress.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.botpress.routeName }}
  labels:
    {{- include "vla.labels" . | nindent 4 }}
spec:
  port:
    targetPort: 3000-tcp
  to:
    kind: Service
    name: {{ .Values.botpress.routeName }}
    weight: 100
  wildcardPolicy: None
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
{{ end }}