{{- if eq .Values.botpress.enabled true -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "botpress.fullname" . }}
  labels:
    {{- include "botpress.labels" . | nindent 4 }}
spec:
  path: /
  to:
    kind: Service
    name: {{ include "botpress.fullname" . }}
  port:
    targetPort: 3000
{{- end }}
