{{- if eq .Values.botpress.enabled true -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: "{{ .Values.botpress.name }}"
  {{- if eq .Values.labels_enabled true -}}
  labels:
    build: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
  {{- end }}
spec:
  host: 
  to:
    kind: Service
    name: "{{ .Values.botpress.name }}"
{{- end }}