kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.botpress.name }}"
  annotations:
    description: Exposes and load balances the application pods
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 3000
  selector:
    name: "{{ .Values.botpress.name }}"