{{- if eq .Values.botpress.enabled true -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.botpress.name }}
  {{- if .Values.labels_enabled }}
  labels:
    build: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
  {{- end }}
  annotations:
    description: Exposes and load balances the application pods
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    name: { .Values.botpress.name }}
{{- end }}