kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.botpress.name }}"
  # labels:
  #   {{- include "project.labels" . | nindent 4 }}
  annotations:
    description: Exposes and load balances the application pods
spec:
  ports:
  - name: web
    port: 3080
    targetPort: 3000
  # selector:
  #   {{- include "project.selectorLabels" . | nindent 4 }}