{{- if eq .Values.chitchat.enabled true -}}
{{- if eq .Values.chitchat.build_enabled true -}}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "{{ .Values.chitchat.name }}"
  {{- if .Values.labels_enabled }}
  labels:
    build: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
  {{- end }}
  annotations:
    description: Defines how to build the application
spec:
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: NLTK_DATA
          value: /root
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.chitchat.name }}:latest
  # TODO : automate dockerfile update
  source:
    type: Dockerfile
    dockerfile: >-
dockerfile: >-
      FROM continuumio/miniconda3


      WORKDIR /app


      RUN git clone --branch hotfix-branch
      https://github.com/eddiebarry/WHO-FAQ-Chitchat-API.git


      WORKDIR /app/WHO-FAQ-Chitchat-API


      RUN conda env create -f env.yaml


      RUN git clone https://github.com/facebookresearch/fastText.git


      WORKDIR /app/WHO-FAQ-Chitchat-API/fastText

      RUN apt-get update

      RUN apt install -y g++

      RUN /opt/conda/envs/myenv/bin/pip install .


      WORKDIR /app/WHO-FAQ-Chitchat-API

      SHELL ["conda", "run", "--no-capture-output", "-n", "myenv", "python",
      "download_weights.py"]

      ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "myenv",
      "gunicorn", "--worker-class", "gevent", "--bind", "0.0.0.0:5001",
      "wsgi:app", "--workers", "2", "--worker-connections", "2000", "--timeout",
      "60", "--preload"]
  triggers:
  - type: ImageChange
  - type: ConfigChange
  #TODO : on update github
  # - type: GitHub
  #   github:
  #     secret: "cS3AFvpd1DLz7C0VW5OVmJhTnXM0qwuOy4JFtulV"
  # - type: Generic
  #   generic:
  #     secret: "gUE5VbKpAmDhz0dYMx5VkZUGK31jQxgE2uOfazNv"
{{- end }}
{{- end }}