{{- if eq .Values.chitchat.enabled true -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "chitchat.name" . }}
  labels:
    build: {{ include "chitchat.name" . }}
    app: {{ include "chitchat.name" . }}
{{- end }}
