{{- if eq .Values.orchestrator.enabled true -}}
{{- if eq .Values.orchestrator.build_enabled true -}}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "{{ template "orc.name" . }}"
  {{- if .Values.labels_enabled }}
  labels:
    build: {{ template "orc.name" . }}-build
    app: {{ template "orc.name" . }}-app
  {{- end }}
  annotations:
    description: Defines how to build the application
spec:
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: NLTK_DATA
          value: /root
  output:
    to:
      kind: ImageStreamTag
      name: {{ template "orc.name" . }}:latest
  # TODO : automate dockerfile update
  source:
    type: Dockerfile
    dockerfile: >-
      FROM python:3.7

      WORKDIR /usr/src

      RUN git clone --branch feature/cicd-test\
          --recursive https://github.com/eddiebarry/WHOA-FAQ-Answer-Project.git

      WORKDIR /usr/src/WHOA-FAQ-Answer-Project

      RUN pip install -r requirements.txt

      WORKDIR
      /usr/src/WHOA-FAQ-Answer-Project/WHO-FAQ-Search-Engine/variation_generation/variation_generator_model_weights

      RUN  wget -O query_expansion_weights.zip
      https://s3-eu-west-1.amazonaws.com/model.weights.project.interakt/query_expansion_weights.zip
      \
          && unzip query_expansion_weights.zip \
          && rm query_expansion_weights.zip

      WORKDIR /usr/src/WHOA-FAQ-Answer-Project

      EXPOSE 5009


      ENTRYPOINT [ "gunicorn", "--bind", "0.0.0.0:5009", "wsgi:app",
      "--timeout", "600"]


      # gunicorn --bind 0.0.0.0:5009 wsgi:app --timeout 600
  triggers:
  - type: ImageChange
  - type: ConfigChange
  #TODO : on update github
  # - type: GitHub
  #   github:
  #     secret: "cS3AFvpd1DLz7C0VW5OVmJhTnXM0qwuOy4JFtulV"
  # - type: Generic
  #   generic:
  #     secret: "gUE5VbKpAmDhz0dYMx5VkZUGK31jQxgE2uOfazNv"
{{- end }}
{{- end }}