{{- if eq .Values.orchestrator.enabled true -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ template "orc.name" . }}
  {{- if .Values.labels_enabled }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
  {{- end }}
spec:
  host: 
  to:
    kind: Service
    name: "{{ template "orc.name" . }}"
{{- end }}