{{- if eq .Values.orchestrator.enabled true -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.orchestrator.name }}
  {{- if eq .Values.labels_enabled true -}}
  labels:
    build: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
  {{- end }}
  annotations:
    description: Exposes and load balances the application pods
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 5009
  selector:
    name: "{{ .Values.orchestrator.name }}"
{{- end }}