# {{- if eq .Values.orchestrator.enabled true -}}
# apiVersion: image.openshift.io/v1
# kind: ImageStream
# metadata:
#   name: {{ .Values.orchestrator.name }}
#   {{- if .Values.labels_enabled }}
#   labels:
#     build: {{ .Values.orchestrator.name }}-build
#     app: {{ .Values.orchestrator.name }}-app
#   {{- end }}
# {{- end }}
