{{- if eq .Values.redis.enabled true -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-password: '{.data[''database-password'']}'
  {{- if .Values.labels_enabled }}
  labels:
    template: redis-persistent-template  
    build: {{ .Values.redis.name }}-build
    app: {{ .Values.redis.name }}-app
  {{- end }}
  name: {{ template "redis.name" . }}
stringData:
  database-password: {{ .Values.redis.redis_password }}
{{- end }}