{{- if eq .Values.redis.enabled true -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    template: redis-persistent-template
  name: {{ template "redis.name" . }}
  labels:
    build: redis-build
    app: redis-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.volume_capacity }}
{{- end }}