{{- if eq .Values.redis.enabled true -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    template: redis-persistent-template
  name: {{ template "redis.name" . }}
  {{- if .Values.labels_enabled }}
  labels:
    build: {{ .Values.redis.name }}-build
    app: {{ .Values.redis.name }}-app
  {{- end }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.volume_capacity }}
{{- end }}