{{- if eq .Values.redis.enabled true -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    template: redis-persistent-template
  name: {{ template "redis.name" . }}
  {{- if eq .Values.labels_enabled true -}}
  labels:
    build: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
  {{- end }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.volume_capacity }}
{{- end }}