# {{- if eq .Values.redis.enabled true -}}
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     template: redis-persistent-template
#   name: {{ template "redis.name" . }}
#   labels:
#     build: {{ .Chart.Name }}
#     app: {{ .Chart.Name }}
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: {{ .Values.redis.volume_capacity }}
# {{- end }}