# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Values.reranker.serviceName }}
#   labels:
#     {{- include "vla.labels" . | nindent 4 }}
# spec:
#   ports:
#     - port: 8080
#       protocol: TCP
#       targetPort: 5009
#       name: 5009-tcp
#   selector:
#     {{- include "vla.selectorLabels" . | nindent 4 }}
#   sessionAffinity: None
#   type: ClusterIP
# status:
#   loadBalancer: {}