apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels: {{- include "vla.labels" . | nindent 4 }}
  name: {{ .Values.reranker.dcName }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 10
  selector:
    {{- include "vla.selectorLabels" . | nindent 4 }}
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        {{- include "vla.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.image_repository }}/{{ .Values.image_namespace | default .Release.Namespace }}/{{ .Values.image_name }}:{{ .Values.image_tag }}"
      # - image: quay.io/whoacademy/virtual-learning-assistant
        imagePullPolicy: Always
        name: reranker-host
        # name: {{ include "vla.name" . }}
        ports:
        - containerPort: 5009
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          httpGet:
            path: /
            port: 5009
          initialDelaySeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5009
          initialDelaySeconds: 3
          timeoutSeconds: 3
        env:
          - name: APP_ENV
            value: "{{ .Values.environment }}"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange