---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "host.fullname" . }}
  labels:
    {{- include "host.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: 8080-tcp
  selector:
    {{- include "host.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
