{{- if eq .Values.solr.route_enabled true -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ template "solr.name" . }}-route
  {{- if .Values.labels_enabled }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
  {{- end }}
spec:
  host: {{ template "solr.name" . }}-labs-dev.apps.dev.lxp.academy.who.int
  to:
    kind: Service
    name: {{ template "solr.fullname" . }}-service
    weight: 100
  port:
    targetPort: 8983
{{- end }}