kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: solr-new
  namespace: zookeeper-cluster
  selfLink: /apis/apps/v1/namespaces/zookeeper-cluster/statefulsets/solr-new
  uid: 74ef8e79-1529-4007-af92-5a88138e3cd5
  resourceVersion: '31066489'
  generation: 7
  creationTimestamp: '2020-11-03T14:55:05Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2020-11-04T05:38:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:podManagementPolicy': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:app': {}
          'f:serviceName': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
            'f:spec':
              'f:containers':
                'k:{"name":"solr"}':
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/store"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:livenessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:tcpSocket':
                      .: {}
                      'f:port': {}
                    'f:timeoutSeconds': {}
                  'f:env':
                    'k:{"name":"MY_POD_IP"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:fieldRef':
                          .: {}
                          'f:apiVersion': {}
                          'f:fieldPath': {}
                    'k:{"name":"ZK_HOST"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                    'k:{"name":"MY_POD_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:fieldRef':
                          .: {}
                          'f:apiVersion': {}
                          'f:fieldPath': {}
                    'k:{"name":"SOLR_LOGS_DIR"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                    .: {}
                    'k:{"name":"SOLR_HOME"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                    'k:{"name":"MY_POD_NAMESPACE"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:fieldRef':
                          .: {}
                          'f:apiVersion': {}
                          'f:fieldPath': {}
                    'k:{"name":"SOLR_HOST"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"POD_HOST_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:fieldRef':
                          .: {}
                          'f:apiVersion': {}
                          'f:fieldPath': {}
                    'k:{"name":"SOLR_HEAP"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                  'f:readinessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:tcpSocket':
                      .: {}
                      'f:port': {}
                    'f:timeoutSeconds': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8983,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:initContainers':
                .: {}
                'k:{"name":"init-solr-data"}':
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/store"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:command': {}
                  'f:env':
                    .: {}
                    'k:{"name":"SOLR_HOME"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                'k:{"name":"init-solr-logs"}':
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/store"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:command': {}
                  'f:env':
                    .: {}
                    'k:{"name":"SOLR_LOGS_DIR"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                'k:{"name":"init-solr-xml"}':
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/store"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:command': {}
                  'f:env':
                    .: {}
                    'k:{"name":"SOLR_HOME"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
          'f:updateStrategy':
            'f:rollingUpdate':
              .: {}
              'f:partition': {}
            'f:type': {}
          'f:volumeClaimTemplates': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2020-11-04T05:42:14Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:collisionCount': {}
          'f:currentReplicas': {}
          'f:currentRevision': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updateRevision': {}
          'f:updatedReplicas': {}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: solr-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: solr-app
    spec:
      initContainers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: init-solr-data
          command:
            - /bin/sh
            - '-c'
            - >-
              if [ ! -d $SOLR_HOME/lib ] ; then mkdir -p $SOLR_HOME/lib && chown
              -R 8983:8983 $SOLR_HOME ; else true; fi
          env:
            - name: SOLR_HOME
              valueFrom:
                configMapKeyRef:
                  name: solr-cluster-config
                  key: solrHome
          imagePullPolicy: Always
          volumeMounts:
            - name: volsolr
              mountPath: /store
          terminationMessagePolicy: File
          image: busybox
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: init-solr-logs
          command:
            - /bin/sh
            - '-c'
            - >-
              if [ ! -d $SOLR_LOGS_DIR ] ; then mkdir -p $SOLR_LOGS_DIR && chown
              8983:8983 $SOLR_LOGS_DIR ; else true; fi
          env:
            - name: SOLR_LOGS_DIR
              valueFrom:
                configMapKeyRef:
                  name: solr-cluster-config
                  key: solrLogsDir
          imagePullPolicy: Always
          volumeMounts:
            - name: volsolr
              mountPath: /store
          terminationMessagePolicy: File
          image: busybox
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: init-solr-xml
          command:
            - /bin/sh
            - '-c'
            - >-
              if [ ! -f $SOLR_HOME/solr.xml ] ; then cp
              /opt/solr/server/solr/solr.xml $SOLR_HOME/solr.xml;sed -i
              "s/<solr>/<solr><str name='sharedLib'>\/store\/data\/lib<\/str>/g"
              $SOLR_HOME/solr.xml ; else true; fi 
          env:
            - name: SOLR_HOME
              valueFrom:
                configMapKeyRef:
                  name: solr-cluster-config
                  key: solrHome
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: volsolr
              mountPath: /store
          terminationMessagePolicy: File
          image: 'solr:8.1.1'
      containers:
        - resources: {}
          readinessProbe:
            tcpSocket:
              port: 8983
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: solr
          livenessProbe:
            tcpSocket:
              port: 8983
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: SOLR_HOME
              valueFrom:
                configMapKeyRef:
                  name: solr-cluster-config
                  key: solrHome
            - name: POD_HOST_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: SOLR_HOST
              value: $(POD_HOST_NAME)
            - name: SOLR_LOGS_DIR
              valueFrom:
                configMapKeyRef:
                  name: solr-cluster-config
                  key: solrLogsDir
            - name: SOLR_HEAP
              valueFrom:
                configMapKeyRef:
                  name: solr-cluster-config
                  key: solrHeap
            - name: ZK_HOST
              valueFrom:
                configMapKeyRef:
                  name: solr-cluster-config
                  key: zkHost
          ports:
            - name: solrport
              containerPort: 8983
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: volsolr
              mountPath: /store
          terminationMessagePolicy: File
          image: 'solr:8.1.1'
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: volsolr
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 32Gi
        storageClassName: managed-premium
        volumeMode: Filesystem
      status:
        phase: Pending
  serviceName: solrcluster
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
status:
  observedGeneration: 7
  replicas: 5
  readyReplicas: 5
  currentReplicas: 5
  updatedReplicas: 5
  currentRevision: solr-new-58dfbff8bc
  updateRevision: solr-new-58dfbff8bc
  collisionCount: 0
